use_default_settings:
  engines:
    keep_only:
      - bing
      - duckduckgo
      - google

general:
  debug: false
  instance_name: HHC Internal Search

search:
  safe_search: 1
  formats:
    - html
    - json

server:
  secret_key: ultrasecretkey
  bind_address: 0.0.0.0
  limiter: false
  public_instance: false
  image_proxy: false
